version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/vacarme
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - attach_workspace:
          at: ~/vacarme
      - aws-s3/sync:
          from: .
          to: s3://studiovacarme.com
orbs:
  aws-s3: circleci/aws-s3@2.0.0
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
