export const MUTATION_SET_PROJECTS = 'MUTATION_SET_PROJECTS';
export const MUTATION_SET_PROJECT_DETAILS = 'MUTATION_SET_PROJECT_DETAILS';
export const MUTATION_SET_DARK_MODE = 'MUTATION_SET_DARK_MODE';
export const ACTION_POPULATE_PROJECTS = 'ACTION_POPULATE_PROJECTS';
export const ACTION_POPULATE_PROJECT_DETAILS = 'ACTION_POPULATE_PROJECT_DETAILS';
